// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qckosrlvugaopalsumhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFja29zcmx2dWdhb3BhbHN1bWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTA3MDMsImV4cCI6MjA2NzgyNjcwM30.cTFnxujmn6toNArB4tn2BNV4yX1fcS4TCCbGPHqMYY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});